# Form implementation generated from reading ui file 'VentanaPrincipal.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(994, 371)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(360, 10, 631, 281))
        self.tableView.setObjectName("tableView")
        self.botonSalir = QtWidgets.QPushButton(parent=self.centralwidget)
        self.botonSalir.setGeometry(QtCore.QRect(890, 300, 97, 33))
        self.botonSalir.setObjectName("botonSalir")
        self.botonEliminar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.botonEliminar.setGeometry(QtCore.QRect(770, 300, 97, 33))
        self.botonEliminar.setObjectName("botonEliminar")
        self.labelUsuario = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelUsuario.setGeometry(QtCore.QRect(30, 70, 91, 21))
        self.labelUsuario.setObjectName("labelUsuario")
        self.labelPass = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelPass.setGeometry(QtCore.QRect(30, 120, 111, 16))
        self.labelPass.setObjectName("labelPass")
        self.lineUsuario = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineUsuario.setGeometry(QtCore.QRect(160, 70, 171, 31))
        self.lineUsuario.setObjectName("lineUsuario")
        self.linePass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.linePass.setGeometry(QtCore.QRect(160, 110, 171, 31))
        self.linePass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.linePass.setObjectName("linePass")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(160, 160, 171, 31))
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(36, 170, 71, 20))
        self.label_2.setObjectName("label_2")
        self.checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(40, 230, 95, 21))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(40, 270, 95, 21))
        self.checkBox_2.setObjectName("checkBox_2")
        self.botonLimpiar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.botonLimpiar.setGeometry(QtCore.QRect(230, 240, 97, 33))
        self.botonLimpiar.setObjectName("botonLimpiar")
        self.botonInsertar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.botonInsertar.setGeometry(QtCore.QRect(650, 300, 97, 33))
        self.botonInsertar.setObjectName("botonInsertar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.botonSalir.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VentanaPrincipal"))
        self.botonSalir.setText(_translate("MainWindow", "SALIR"))
        self.botonEliminar.setText(_translate("MainWindow", "ELIMINAR"))
        self.labelUsuario.setText(_translate("MainWindow", "USUARIO"))
        self.labelPass.setText(_translate("MainWindow", "CONTRASEÑA"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Inserte una opción"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Alumno"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Profesor"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Administrador"))
        self.label_2.setText(_translate("MainWindow", "TIPO"))
        self.checkBox.setText(_translate("MainWindow", "PRIMERO"))
        self.checkBox_2.setText(_translate("MainWindow", "SEGUNDO"))
        self.botonLimpiar.setText(_translate("MainWindow", "LIMPIAR"))
        self.botonInsertar.setText(_translate("MainWindow", "INSERTAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
